# Generated by Django 6.0.3 on 2026-05-04 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('ativo', models.BooleanField(default=True)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('duracao_minutos', models.PositiveIntegerField(default=60)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='agendamento',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('presente', 'Presente'), ('ausente', 'Ausente')], default='pendente', max_length=10),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='descricao',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='HorarioBloqueado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('bloqueio', 'Bloqueio'), ('liberado', 'Liberado')], max_length=10)),
            ],
            options={
                'unique_together': {('data', 'horario')},
            },
        ),
        migrations.AddField(
            model_name='agendamento',
            name='servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agendamento.servico'),
        ),
        migrations.AddConstraint(
            model_name='agendamento',
            constraint=models.UniqueConstraint(fields=('data', 'horario'), name='unique_agendamento_data_horario'),
        ),
    ]
